/** 全部用户可见文案。集中放这里，未来做 i18n 时按命名空间拆。 */

export const strings = {
  appName: 'RSS Reader',
  appTagline: '自托管 RSS 阅读器',
  loading: '加载中…',
  empty: '这里还没有内容',
  error: '出错了',
  retry: '重试',
  cancel: '取消',
  save: '保存',
  confirm: '确定',
  delete: '删除',
  edit: '编辑',
  search: '搜索',

  auth: {
    login: '登录',
    signup: '注册',
    loginHint: '登录后继续阅读你订阅的内容',
    signupHint: '注册后数据只保存在本机',
    email: '邮箱',
    password: '密码',
    username: '用户名',
    skip: '跳过，以 user 身份进入',
    localNote: '账户与订阅数据仅保存在本地，可在「设置 → 订阅源」中导出。',
    failed: '邮箱或密码错误',
    registered: '该邮箱已注册',
  },

  nav: {
    all: '全部',
    essays: '文章',
    pictures: '图片',
    videos: '视频',
    favorites: '收藏夹',
    favoritesItem: '收藏',
    folders: 'RSS 目录',
    ungrouped: '未分组源',
    stats: '分组统计',
    newFolder: '新建目录',
    folderName: '目录名',
    emptyFolders: '还没有目录',
    searchPlaceholder: '搜索订阅源与文章',
  },

  list: {
    refresh: '刷新',
    markAllRead: '全部标记已读',
    showAll: '全部',
    showUnread: '未读',
    showRead: '已读',
    unreadSummary: (unread: number, feeds: number) => `${unread} 篇未读 · ${feeds} 个订阅源`,
    pictureSummary: (count: number, feeds: number) => `${count} 张新图片 · ${feeds} 个源`,
    videoSummary: (count: number, feeds: number) => `${count} 个新视频 · ${feeds} 个频道`,
    favoriteSummary: (count: number) => `${count} 条收藏`,
    folderSummary: (count: number) => `${count} 篇未读`,
    noMore: '没有更多了',
    refreshDone: (n: number) => (n > 0 ? `已更新 ${n} 篇` : '没有新内容'),
  },

  article: {
    progress: (read: number, total: number) =>
      `阅读进度 ${read.toLocaleString('zh-CN')} / ${total.toLocaleString('zh-CN')} 字`,
    markRead: '标记为已读',
    markUnread: '标记为未读',
    favorite: '收藏',
    unfavorite: '取消收藏',
    share: '分享',
    linkCopied: '链接已复制',
    exportPdf: '导出 PDF',
    exportMarkdown: '导出 Markdown',
    author: '作者',
    minutes: '约 {n} 分钟',
    prev: '上一篇',
    next: '下一篇',
    openOriginal: '打开原文',
  },

  profile: {
    title: '个人资料',
    username: '用户名',
    email: '邮箱',
    emailLocked: '邮箱为身份标识，不可编辑',
    colorHint: '默认头像为用户首字母 + 纯色背景',
    upload: '从本地上传',
    uploadHint: '支持 png / jpg，文件不超过 3MB',
    removeImage: '恢复首字母头像',
    exportData: '导出我的数据 (JSON)',
    menuProfile: '个人资料',
    menuSettings: '设置',
    menuLogout: '退出登录',
    saved: '已保存',
    tooLarge: '文件不能超过 3MB',
    badImage: '只支持 png / jpg 图片',
  },

  settings: {
    title: '设置',
    subtitle: '全部数据保存在本地',
    tabAppearance: '外观',
    tabRss: '订阅源',
    tabAi: 'AI',
    tabIntegrations: '集成',
    tabAutomation: '自动化',
    tabProxy: '代理',
    comingSoon: '后续版本支持',
    comingSoonHint: '该功能已在路线图中，本版本暂未实现。',
    appearanceTitle: '外观',
    appearanceSubtitle: '修改后即时生效，仅影响本机显示',
    theme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    language: '语言',
    textStyle: '正文字号',
    textSmall: '小',
    textComfortable: '舒适',
    textLarge: '大',
    refresh: '自动刷新',
    refreshHint: '定时拉取订阅源的新内容',
    refreshInterval: '刷新间隔（分钟）',
    rssTitle: '订阅源',
    rssSubtitle: '修改后即时生效，仅影响本机显示',
    dataManagement: '数据管理',
    exportOpml: '导出订阅源',
    exportOpmlHint: 'OPML 格式，可导入到其它阅读器',
    importOpml: '导入订阅源',
    importOpmlHint: '支持 OPML / JSON 文件',
    exportRead: '导出阅读数据',
    exportReadHint: '含已读、收藏与阅读进度（JSON）',
    clearData: '清空本地数据',
    clearDataHint: '删除本机全部订阅与阅读记录',
    clearConfirm: '确认清空全部本地数据？此操作不可撤销，请先做好导出。',
    manage: '管理订阅',
    addFeed: '添加订阅',
    editFeed: '编辑',
    deleteSelected: '删除',
    feedUrl: '订阅地址',
    feedTitle: '显示名称',
    feedFolder: '目录',
    feedColSource: '源',
    feedColUrl: '地址',
    feedColFolder: '目录',
    feedColStatus: '状态',
    statusEnabled: '已启用',
    statusPaused: '已暂停',
    statusError: '抓取失败',
    selectAll: '全选',
    importDone: (imported: number, skipped: number) =>
      skipped > 0 ? `导入 ${imported} 个，跳过 ${skipped} 个` : `导入 ${imported} 个订阅源`,
    deleteConfirm: (n: number) => `确认删除选中的 ${n} 个订阅源？`,
    noFeeds: '还没有订阅源，点击「添加订阅」开始',
  },

  ai: {
    providers: '供应商',
    addProvider: '添加供应商',
    fieldUrl: '接口地址 (url)',
    fieldKey: 'API Key',
    fieldModel: '模型',
    keyPlaceholder: '无需密钥',
    noProviders: '还没有 AI 供应商，点「添加供应商」开始',
    deleteConfirm: (label: string) => `删除供应商「${label}」？`,
    customOption: '自定义',
    usageTitle: 'Token 使用量',
    usageUsed: '本月已用',
    usageTokens: 'tokens',
    usageUnlimited: '不限',
    usageHint: '达到上限后将暂停 AI 总结与翻译',
    limitLabel: '设置上限（tokens）',
    limitPlaceholder: '0 表示不限',
    summarize: 'AI 总结',
    translate: '标题翻译',
    generating: '生成中…',
    summaryTitle: 'AI 总结',
    caseTranslation: '标题翻译',
    cacheHint: '已缓存，不会重复消耗 token',
    firstProviderHint: '多个供应商同时开启时，使用列表里第一个。',
  },
} as const;
